Throw error if the factory being build is not defined.
The current exception is:
     TypeError: Cannot call method 'build' of undefined
which is not very informative.